version: "3.9"
services:
  torch:
    # image: pytorch/pytorch
    init: true
    build:
      context: ./
      dockerfile: pytorch.Dockerfile
    ports:
      - "8888:8888"
      - "6006:6006"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    command: jupyter notebook --ip 0.0.0.0 --no-browser --allow-root --NotebookApp.token=mysup3rtok3n
